// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX8B5m9QK4zCpt-BTyDXyx8PT6HBtsEC8',
    appId: '1:311505525303:web:d39a62271cfd0a9c42fdb2',
    messagingSenderId: '311505525303',
    projectId: 'rydo-dddae',
    authDomain: 'rydo-dddae.firebaseapp.com',
    storageBucket: 'rydo-dddae.firebasestorage.app',
    measurementId: 'G-GX2LQ5QMKS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLaOWYWd5NOap5P7KvLELzgV3yHff-AOk',
    appId: '1:311505525303:ios:ba27c27924d63b6742fdb2',
    messagingSenderId: '311505525303',
    projectId: 'rydo-dddae',
    storageBucket: 'rydo-dddae.firebasestorage.app',
    iosBundleId: 'com.example.rydo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLaOWYWd5NOap5P7KvLELzgV3yHff-AOk',
    appId: '1:311505525303:ios:ba27c27924d63b6742fdb2',
    messagingSenderId: '311505525303',
    projectId: 'rydo-dddae',
    storageBucket: 'rydo-dddae.firebasestorage.app',
    iosBundleId: 'com.example.rydo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX8B5m9QK4zCpt-BTyDXyx8PT6HBtsEC8',
    appId: '1:311505525303:web:eb48d5bc9eb63fc142fdb2',
    messagingSenderId: '311505525303',
    projectId: 'rydo-dddae',
    authDomain: 'rydo-dddae.firebaseapp.com',
    storageBucket: 'rydo-dddae.firebasestorage.app',
    measurementId: 'G-61NE15R2F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBrOSThQ0CRQrvZHrmXakZGf_FqV1ecr0',
    appId: '1:311505525303:android:0c901d38175bab7642fdb2',
    messagingSenderId: '311505525303',
    projectId: 'rydo-dddae',
    storageBucket: 'rydo-dddae.firebasestorage.app',
  );

}